name: Make a Release from a Tag

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
      runs-on: macos-13
      timeout-minutes: 10
      steps:
      - uses: actions/checkout@v4
      - name: Set Environment
        run: sudo xcrun xcode-select -s /Applications/Xcode_15.2.app
      - name: Update Build Number
        env:
          TAG_NAME: ${{ github.ref }}
          RUN_ID: ${{ github.run_id }}
        run: |
            export CLEAN_TAG=$(echo $TAG_NAME | sed -e 's/refs\/tags\///')
            cd Scripts && swift Bump.swift $CLEAN_TAG 1.$RUN_ID
      - name: Build
        run: cd Scripts && swift Build.swift
      - name: Create ZIPs
        run: |
            ditto -c -k --sequesterRsrc --keepParent Scripts/Archive.xcarchive/Products/Applications/eikana.app ./eikana.zip
      - name: Get the file hash sha256 of the ZIP
        run: |
            shasum -a 256 eikana.zip
      - name: Create a new Release and Upload App
        uses: softprops/action-gh-release@v2
        with:
          files: eikana.zip
          body: |
            Update description
            
            ## Features
            
            ## Fixes
            
            ## Minimum macOS Version
          draft: true